### PR TITLE
Add presence

### PR DESCRIPTION
**Pull request by gieljnssns**
my HA fork https://github.com/gieljnssns/home-assistant/tree/netatmo-presence

### CODE REVIEW

**Comment by gieljnssns** [comment]
I just got this error:
```
16-12-10 16:26:02 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/Users/giel/Github/home-assistant/homeassistant/helpers/entity_component.py", line 386, in _update_entity_states
    yield from update_coro
  File "/Users/giel/Github/home-assistant/homeassistant/helpers/entity.py", line 213, in async_update_ha_state
    yield from self.hass.loop.run_in_executor(None, self.update)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/giel/Github/home-assistant/homeassistant/components/binary_sensor/netatmo.py", line 167, in update
    self._data.update_event()
  File "/Users/giel/Github/home-assistant/homeassistant/util/__init__.py", line 296, in wrapper
    result = method(*args, **kwargs)
  File "/Users/giel/Github/home-assistant/homeassistant/components/netatmo.py", line 121, in update_event
    home=self.home, cameratype=self.camera_type)
  File "/Users/giel/.homeassistant/deps/smart_home/Camera.py", line 239, in updateEvent
    resp = postRequest(_GETEVENTSUNTIL_REQ, postParams)
  File "/Users/giel/.homeassistant/deps/smart_home/__init__.py", line 27, in postRequest
    resp = urllib.request.urlopen(req, params).read(body_size).decode("utf-8")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```
Everything still works.

**Comment by gieljnssns** [comment]
```
16-12-11 01:24:36 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/Users/giel/Github/home-assistant/homeassistant/helpers/entity_component.py", line 386, in _update_entity_states
    yield from update_coro
  File "/Users/giel/Github/home-assistant/homeassistant/helpers/entity.py", line 213, in async_update_ha_state
    yield from self.hass.loop.run_in_executor(None, self.update)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/giel/Github/home-assistant/homeassistant/components/binary_sensor/netatmo.py", line 167, in update
    self._data.update_event()
  File "/Users/giel/Github/home-assistant/homeassistant/util/__init__.py", line 296, in wrapper
    result = method(*args, **kwargs)
  File "/Users/giel/Github/home-assistant/homeassistant/components/netatmo.py", line 121, in update_event
    home=self.home, cameratype=self.camera_type)
  File "/Users/giel/.homeassistant/deps/smart_home/Camera.py", line 239, in updateEvent
    resp = postRequest(_GETEVENTSUNTIL_REQ, postParams)
  File "/Users/giel/.homeassistant/deps/smart_home/__init__.py", line 27, in postRequest
    resp = urllib.request.urlopen(req, params).read(body_size).decode("utf-8")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
16-12-11 01:26:45 INFO (MainThread) [homeassistant.components.http] Serving /api/camera_proxy/camera.den_hof to 192.168.0.29 (auth: True)
16-12-11 01:28:37 INFO (MainThread) [homeassistant.components.http] Serving /api/camera_proxy/camera.den_hof to 192.168.0.29 (auth: True)
16-12-11 01:31:05 INFO (MainThread) [homeassistant.components.http] Serving /api/camera_proxy/camera.den_hof to 192.168.0.29 (auth: True)
16-12-11 01:32:57 INFO (MainThread) [homeassistant.components.http] Serving /api/camera_proxy/camera.den_hof to 192.168.0.29 (auth: True)
16-12-11 01:35:25 INFO (MainThread) [homeassistant.components.http] Serving /api/camera_proxy/camera.den_hof to 192.168.0.29 (auth: True)
16-12-11 01:37:17 INFO (MainThread) [homeassistant.components.http] Serving /api/camera_proxy/camera.den_hof to 192.168.0.29 (auth: True)
16-12-11 01:37:42 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/Users/giel/Github/home-assistant/homeassistant/helpers/entity_component.py", line 386, in _update_entity_states
    yield from update_coro
  File "/Users/giel/Github/home-assistant/homeassistant/helpers/entity.py", line 213, in async_update_ha_state
    yield from self.hass.loop.run_in_executor(None, self.update)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/giel/Github/home-assistant/homeassistant/components/binary_sensor/netatmo.py", line 167, in update
    self._data.update_event()
  File "/Users/giel/Github/home-assistant/homeassistant/util/__init__.py", line 296, in wrapper
    result = method(*args, **kwargs)
  File "/Users/giel/Github/home-assistant/homeassistant/components/netatmo.py", line 121, in update_event
    home=self.home, cameratype=self.camera_type)
  File "/Users/giel/.homeassistant/deps/smart_home/Camera.py", line 239, in updateEvent
    resp = postRequest(_GETEVENTSUNTIL_REQ, postParams)
  File "/Users/giel/.homeassistant/deps/smart_home/__init__.py", line 27, in postRequest
    resp = urllib.request.urlopen(req, params).read(body_size).decode("utf-8")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by jabesq** [comment]
These error are home-assistant related so I won't fix it here. This GitHub is only for the netatmo API which is currently working fine. 

An error 502 might be an error from the netatmo servers

**Comment by gieljnssns** [comment]
Do I have to resolve those conflicts?
setup.py
Welcome.py
Or will you do that?
setup.py -> Change the version number to ?
Welcome.py -> ?

**Comment by jabesq** [comment]
Yes, you have to fix your merge conflict, except for setup.py I'll update it when I'll create a new tag/release

**Comment by gieljnssns** [comment]
How must i fix this? 
smart_home/Welcome.py
I renamed it to Camera.py

**Comment by jabesq** [comment]
it would easier for you if you rebase or merge on top of my origin/master
git remote add upstream git@github.com:jabesq/netatmo-api-python.git
git fetch upstream
git rebase upstream/master (or git merge upstream/master)

**Pull request merged**
