### PR TITLE
Add GetPublicData call

### PR DESCRIPTION
**Pull request by colinfrei**
I have almost no Python knowledge, and just scratched together what I could. Even I can tell that some of this could be much nicer... I'm just trying to at least get something to work.

Most of the PublicData class is copied from https://github.com/SebastienPittet/netatmo-api-python/blob/master/lnetatmo.py and seems to have been written by @SebastienPittet

### CODE REVIEW

**Comment by jabesq** [comment]
Looks good to me

**Comment by SebastienPittet** [comment]
Thanks for the mention :-) .

**Comment by colinfrei** [comment]
Thanks!

Could you do whatever needs to be done to make the newer version available via pip: https://pypi.org/project/pyatmo/#history

Not sure if that just means tagging a version or if there's more to it...

**Comment by jabesq** [comment]
I just released it on pypi as version 1.1 https://pypi.org/project/pyatmo/

**Pull request merged**
